export const FETCHING_ACTION = 'FETCHING_ACTION';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const REMOVE_BOOK = 'REMOVE_BOOK';
export const ADD_BOOK = 'ADD_BOOK';
export const RENAME_AUTHOR = 'RENAME_AUTHOR';